"""
Django settings for specials project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from django.contrib.messages import constants as message_constants
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent

default_log_dir = Path(os.getenv("APP_LOG_DIR", "/tmp/appertivo/logs"))
APP_LOG_FILE = Path(os.getenv("APP_LOG_FILE", str(default_log_dir / "app-log.json")))
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
USE_CLOUDINARY_STORAGE = bool(
    CLOUDINARY_URL
    or (CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET)
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9p1o@*d)+lij5nyyv6=8i*m^r_gmn&2(2ol-twbzpyf9#v&f4w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "appertivo.com", "www.appertivo.com",
    "app.appertivo.com", "localhost", "127.0.0.1", "38.68.10.226",
    "*"  # Allow all hosts for Replit development environment
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'cloudinary',
    'django_extensions',
    'corsheaders',
    'django_crontab',
    'app.apps.AppConfig',
    'anymail',
    "django_htmx",
    'appertivo.leads.apps.LeadsConfig',
    'appertivo.assets.apps.AssetsConfig',
    'articles.apps.ArticlesConfig',
    'swipe.apps.SwipeConfig',
]

if USE_CLOUDINARY_STORAGE and 'cloudinary_storage' not in INSTALLED_APPS:
    INSTALLED_APPS.append('cloudinary_storage')

# Map Django message levels to Bootstrap alert classes
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}


def _env_int(name: str, default: int) -> int:
    """Read an integer from environment variables with a fallback."""

    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_PRICE_ID = os.getenv("STRIPE_PRICE_ID", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_TRIAL_DAYS = _env_int("STRIPE_TRIAL_DAYS", 14)
STRIPE_PLAN_CODE = os.getenv("STRIPE_PLAN_CODE", "pro")
STRIPE_API_KEY = STRIPE_SECRET_KEY

RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'specials.urls'

# CSRF origin checking (must include scheme; wildcard ok for subdomains)
CSRF_TRUSTED_ORIGINS = [
    "https://appertivo.com",
    "https://www.appertivo.com",
    "https://*.appertivo.com",
]

# # If you want cookies valid across subdomains (optional)
# CSRF_COOKIE_DOMAIN = ".appertivo.com"
# SESSION_COOKIE_DOMAIN = ".appertivo.com"

# If you're behind Cloudflare/Tunnel or any proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Security best practices in prod
if DEBUG:
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Custom template folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'specials.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

ACCOUNT_FORMS = {
    "signup": "app.forms.SignUpForm",
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# STATIC FILES
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic

# MEDIA FILES
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

if USE_CLOUDINARY_STORAGE:
    cloudinary_storage_config = {
        key: value
        for key, value in {
            "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
            "API_KEY": CLOUDINARY_API_KEY,
            "API_SECRET": CLOUDINARY_API_SECRET,
        }.items()
        if value
    }
    if cloudinary_storage_config:
        CLOUDINARY_STORAGE = cloudinary_storage_config
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    media_url_override = os.getenv("CLOUDINARY_MEDIA_URL")
    if media_url_override:
        MEDIA_URL = media_url_override
    elif CLOUDINARY_CLOUD_NAME:
        MEDIA_URL = f"https://res.cloudinary.com/{CLOUDINARY_CLOUD_NAME}/"

# DEFAULT PRIMARY KEY
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
# Enable in-process execution when a broker isn't available (dev-friendly)
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "0").lower() in {"1", "true", "yes"}


CELERY_BEAT_SCHEDULE = {
    "leads-fetch-weekly": {
        "task": "appertivo.leads.tasks.fetch_leads",
        "schedule": timedelta(weeks=1),
        "options": {"expires": 60 * 60 * 24},
    },
}

Q_CLUSTER = {
    "name": "articles",
    "workers": 2,
    "timeout": 120,
    "retry": 120,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
        },
        "app_json": {
            "level": "INFO",
            "class": "specials.logging_handlers.DailyJsonFileHandler",
            "filename": str(APP_LOG_FILE),
        },
    },
    "root": {
        "handlers": ["console", "app_json"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_json"],
            "level": "INFO",
            "propagate": True,
        },
        "app": {  # your app name here
            "handlers": ["console", "app_json"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

SERVER_EMAIL = 'ian.larsen.1976@gmail.com'
DEFAULT_FROM_EMAIL = 'ian@appertivo.com'
LOGIN_URL = reverse_lazy("login")
LOGIN_REDIRECT_URL = reverse_lazy("swipe:home")

LOGOUT_REDIRECT_URL = reverse_lazy("login")
SITE_ID=1
BREVO_API_KEY = os.getenv('BREVO_API_KEY')
# if BREVO_API_KEY:
EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
ANYMAIL = {'BREVO_API_KEY': BREVO_API_KEY}


LLM_COST_TRACKING_ENABLED = True

LLM_PRICING = {
    "openai": {
        "gpt-4.1-mini": {
            "input_per_1k": Decimal("0.00015"),
            "output_per_1k": Decimal("0.00060"),
        },
        "gpt-4o-mini": {
            "input_per_1k": Decimal("0.00015"),
            "output_per_1k": Decimal("0.00060"),
        },
        "gpt-4.1-nano": {
            "input_per_1k": Decimal("0.00004"),
            "output_per_1k": Decimal("0.00016"),
        },
        "gpt-4.1": {
            "input_per_1k": Decimal("0.00250"),
            "output_per_1k": Decimal("0.01000"),
        },
        "dall-e-3": {"per_call": Decimal("0.04000")},
    },
    "gemini": {
        "gemini-2.5-flash-image-preview": {"per_call": Decimal("0.03900")},
    },
}


CRONJOBS = [("0 * * * *", "app.cron.unpublish_expired_specials")]

for _app in ['django_extensions', 'corsheaders', 'anymail', 'cloudinary', 'cloudinary_storage', 'django_crontab']:
    try:
        __import__(_app)
    except ModuleNotFoundError:
        if _app in INSTALLED_APPS:
            INSTALLED_APPS.remove(_app)

if "corsheaders" not in INSTALLED_APPS and "corsheaders.middleware.CorsMiddleware" in MIDDLEWARE:
    MIDDLEWARE.remove("corsheaders.middleware.CorsMiddleware")
