# Generated by Django 5.2.7 on 2025-10-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_restaurant_menu_urls_and_more'),
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='app.restaurant'),
        ),
    ]
