# Generated by Django 5.2.7 on 2025-10-14 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swipe", "0003_alter_concept_restaurant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(choices=[("concept", "Concept"), ("dish", "Dish")], max_length=20)),
                ("item_id", models.PositiveIntegerField()),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "item_type", "item_id")},
            },
        ),
        migrations.AddIndex(
            model_name="seenitem",
            index=models.Index(fields=["user", "item_type"], name="swipe_seen_user_ty_2ed7a6_idx"),
        ),
        migrations.AddIndex(
            model_name="seenitem",
            index=models.Index(fields=["item_type", "item_id"], name="swipe_seen_item_ty_8d4932_idx"),
        ),
    ]
