# Generated by Django 5.2.7 on 2025-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swipe", "0004_seenitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
