# Generated by Django 5.2.7 on 2025-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swipe", "0005_concept_is_favorite_dish_is_favorite"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="seenitem",
            new_name="swipe_seeni_user_id_f05786_idx",
            old_name="swipe_seen_user_ty_2ed7a6_idx",
        ),
        migrations.RenameIndex(
            model_name="seenitem",
            new_name="swipe_seeni_item_ty_3187dc_idx",
            old_name="swipe_seen_item_ty_8d4932_idx",
        ),
        migrations.AddField(
            model_name="concept",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
