# Generated by Django 5.2.7 on 2025-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "swipe",
            "0006_rename_swipe_seen_user_ty_2ed7a6_idx_swipe_seeni_user_id_f05786_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
