# Generated by Django 5.2.7 on 2025-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_assetfolder_generatedasset_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetfolder",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assetfolder",
            name="pin",
            field=models.CharField(default="5250", max_length=4),
        ),
    ]
