# Generated by Django 5.2.7 on 2025-10-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_assetfolder_is_locked_assetfolder_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetpreviewjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetpreviewjob",
            name="prediction_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="assetpreviewjob",
            name="replicate_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
