# Generated by Django 5.2.6 on 2025-09-15 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("rank_order", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MenuVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                (
                    "source_kind",
                    models.TextField(
                        choices=[
                            ("url_scrape", "Url Scrape"),
                            ("pasted_text", "Pasted Text"),
                            ("image_ocr", "Image Ocr"),
                        ]
                    ),
                ),
                ("raw_markdown", models.TextField()),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("limits", models.JSONField()),
                ("features", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagDictionary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.TextField(choices=[("category", "Category")])),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.TextField(
                        choices=[("image", "Image"), ("pdf", "Pdf"), ("other", "Other")]
                    ),
                ),
                ("storage_key", models.TextField()),
                ("public_url", models.TextField()),
                ("width_px", models.IntegerField(blank=True, null=True)),
                ("height_px", models.IntegerField(blank=True, null=True)),
                ("format", models.TextField(blank=True, null=True)),
                ("blurhash", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"], name="app_asset_kind_a3fdff_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DishIdea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("ingredient_names", models.JSONField(default=list)),
                ("category_tags", models.JSONField(default=list)),
                (
                    "parent_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.concept"
                    ),
                ),
                (
                    "parent_dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dishidea",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Enhancement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                ("suggested_price_cents", models.IntegerField(blank=True, null=True)),
                ("currency", models.TextField(default="USD")),
                ("pricing_notes", models.TextField(blank=True, null=True)),
                ("style_preset", models.TextField(blank=True, null=True)),
                ("model_name", models.TextField()),
                ("cost_cents", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dishidea"
                    ),
                ),
                (
                    "image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.asset",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdeationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.TextField(
                        choices=[("concepts", "Concepts"), ("dishes", "Dishes")]
                    ),
                ),
                ("model_name", models.TextField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=3)),
                ("classic_creative", models.SmallIntegerField()),
                ("context_snapshot", models.JSONField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                ("cost_cents", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "initiated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.concept",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dishidea",
            name="ideation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.ideationrun"
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="ideation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.ideationrun"
            ),
        ),
        migrations.CreateModel(
            name="NotificationPref",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("on_background_complete_email", models.BooleanField(default=True)),
                ("on_new_menu_version_email", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("location_text", models.TextField()),
                ("primary_menu_url", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
                (
                    "active_menu_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.menuversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutscraperPayload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                ("request_params", models.JSONField()),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("discovered_menu_url", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuversion",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
            ),
        ),
        migrations.CreateModel(
            name="MenuCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("outscraper", "Outscraper"),
                            ("menu_scrape", "Menu Scrape"),
                            ("ingredient_build", "Ingredient Build"),
                            ("ideation", "Ideation"),
                            ("image_generate", "Image Generate"),
                            ("email_send", "Email Send"),
                        ]
                    ),
                ),
                ("ref_table", models.TextField()),
                ("ref_id", models.UUIDField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                ("progress_pct", models.SmallIntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("canonical_name", models.TextField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                (
                    "first_seen_menu_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.menuversion",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ideationrun",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="dishidea",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
            ),
        ),
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("classic_creative_slider", models.SmallIntegerField(default=50)),
                ("default_currency", models.TextField(default="USD")),
                ("llm_defaults", models.JSONField(default=dict)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.TextField(
                        choices=[("stripe", "Stripe"), ("manual", "Manual")]
                    ),
                ),
                ("provider_customer_id", models.TextField()),
                ("provider_sub_id", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ]
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UiEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                (
                    "entity_type",
                    models.TextField(
                        choices=[
                            ("concept", "Concept"),
                            ("dish", "Dish"),
                            ("menu", "Menu"),
                            ("enhancement", "Enhancement"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("extra", models.JSONField(default=dict)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("timezone", models.TextField(default="America/Los_Angeles")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntitlementCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateField()),
                ("concept_runs", models.IntegerField(default=0)),
                ("dish_runs", models.IntegerField(default=0)),
                ("enhancements", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteConcept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("favorited_at", models.DateTimeField()),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.concept"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "concept")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteDish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("favorited_at", models.DateTimeField()),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dishidea"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dish")},
            },
        ),
        migrations.CreateModel(
            name="DishIdeaIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.TextField(
                        choices=[("overlap", "Overlap"), ("inferred", "Inferred")]
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dishidea"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.ingredient"
                    ),
                ),
            ],
            options={
                "unique_together": {("dish", "ingredient", "source")},
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "user")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.SmallIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dishidea"
                    ),
                ),
                (
                    "enhancement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.enhancement",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.menucollection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["menu", "position"],
                        name="app_menuite_menu_id_ffff97_idx",
                    )
                ],
                "unique_together": {("menu", "dish")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("job_complete", "Job Complete"),
                            ("enhancement_ready", "Enhancement Ready"),
                            ("menu_rescraped", "Menu Rescraped"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                (
                    "channel",
                    models.TextField(
                        choices=[("email", "Email"), ("in_app", "In App")]
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ]
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="app_notific_user_id_518f18_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["account", "name"], name="app_restaur_account_48b45b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outscraperpayload",
            index=models.Index(
                fields=["restaurant", "-created_at"],
                name="app_outscra_restaur_e52916_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuversion",
            index=models.Index(
                fields=["restaurant", "-created_at"],
                name="app_menuver_restaur_f69dc1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="menucollection",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_collection"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["account", "status", "-created_at"],
                name="app_job_account_e2774a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(fields=["name"], name="app_ingredi_name_e448be_idx"),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_restaurant_ingredient"
            ),
        ),
        migrations.AddIndex(
            model_name="ideationrun",
            index=models.Index(
                fields=["restaurant", "type", "-created_at"],
                name="app_ideatio_restaur_5397e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["restaurant", "-created_at"],
                name="app_concept_restaur_6d9e4e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["trialing", "active", "past_due"])),
                fields=("account",),
                name="unique_live_subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="uievent",
            index=models.Index(
                fields=["user", "-created_at"], name="app_uievent_user_id_dbdcbc_idx"
            ),
        ),
    ]
