# Generated by Django 5.2.5 on 2025-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='context_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='google_place_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
