# Generated by Django 4.1.5 on 2025-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="google_post_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
