# Generated by Django 5.2.7 on 2025-10-07 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_onboarding_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
