# Generated by Django 5.2.5 on 2025-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurant_about_json_restaurant_context_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
