# Generated by Django 5.2.6 on 2025-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_concept_subtitle_alter_concept_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="sketch_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
