# Generated by Django 5.2.7 on 2025-10-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_onboarding_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='about_json',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='active_menu_version',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='context_json',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='hours_json',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='review_count',
        ),
    ]
