# Generated by Django 5.2.7 on 2025-10-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_restaurant_about_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_urls',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='primary_menu_url',
        ),
    ]
