# Generated by Django 5.2.5 on 2025-09-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_concept_sketch_image_url'),
        ('app', '0004_restaurant_menu_urls'),
    ]

    operations = [
    ]
