# Generated by Django 5.2.4 on 2025-08-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscription_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
