# Generated by Django 5.2.5 on 2025-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_special_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
