# Generated by Django 5.2.5 on 2025-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20250918_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='reasoning',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
