# Generated by Django 5.2.5 on 2025-08-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_special_image"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_signups",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
