# Generated by Django 5.2.6 on 2025-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_concept_reasoning_concept_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishidea",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
