# Generated by Django 5.2.5 on 2025-08-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_emailsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
