# Generated by Django 5.2.6 on 2025-09-27 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_account_stripe_customer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("passcode", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.menucollection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("thumbs_up", "Thumbs up"),
                            ("thumbs_down", "Thumbs down"),
                            ("comment", "Comment"),
                            ("edit_suggestion", "Suggest edit"),
                            ("reorder", "Reorder"),
                            ("new_idea", "New idea"),
                        ]
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("anon_id", models.TextField()),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dishidea",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="app.collaborationlink",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.menucollection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action",
                        to="app.feedback",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="collaborationlink",
            index=models.Index(
                fields=["menu", "is_active", "expires_at"],
                name="app_collabo_menu_id_bf68d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["menu", "type", "-created_at"],
                name="app_feedbac_menu_id_3d9ae4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackaction",
            index=models.Index(
                fields=["status", "-created_at"], name="app_feedbac_status_c5a10f_idx"
            ),
        ),
    ]
