# Generated by Django 4.1.5 on 2025-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="rrule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
