# Generated by Django 5.2.5 on 2025-08-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_special_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsignup",
            name="special",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_signups",
                to="app.special",
            ),
        ),
        migrations.CreateModel(
            name="SpecialAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens", models.PositiveIntegerField(default=0)),
                ("cta_clicks", models.PositiveIntegerField(default=0)),
                ("email_signups", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "special",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="app.special",
                    ),
                ),
            ],
        ),
    ]
