# Generated by Django 5.2.7 on 2025-11-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_competitive_analysis_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='app_newslet_created_c1965e_idx',
            old_name='app_newslet_created__a642be_idx',
        ),
    ]
