# Generated by Django 5.2.6 on 2025-09-29 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_collaborationlink_feedback_feedbackaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmCallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.TextField()),
                ("model_name", models.TextField()),
                (
                    "call_type",
                    models.TextField(choices=[("text", "Text"), ("image", "Image")]),
                ),
                ("step", models.TextField()),
                ("function_name", models.TextField()),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("cost_cents", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="app_llmcall_created_9e9b54_idx"
                    ),
                    models.Index(
                        fields=["provider", "model_name"],
                        name="app_llmcall_provide_35c4ea_idx",
                    ),
                    models.Index(
                        fields=["user", "step"], name="app_llmcall_user_id_d4c5b0_idx"
                    ),
                ],
            },
        ),
    ]
