# Generated by Django 5.2.5 on 2025-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_special_rrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='html',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='pipeline_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(default='Test', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(default='test', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='tokens_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='tokens_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='usd_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
