# Generated by Django 4.1.5 on 2025-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_special_rrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="formatted_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
