# Generated by Django 5.2.6 on 2025-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_llmcalllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="reviews_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
