# Generated by Django 5.2.5 on 2025-09-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_content_article_html_and_more'),
        ('app', '0010_userprofile_formatted_address_and_more'),
    ]

    operations = [
    ]
