# Generated by Django 5.2.5 on 2025-08-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="account_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="integration",
            name="location_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
