# Generated by Django 5.2.5 on 2025-09-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_concept_is_unfavorite'),
        ('app', '0011_restaurant_reviews_json'),
    ]

    operations = [
    ]
