# Generated by Django 5.2.5 on 2025-09-03 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userprofile_category_userprofile_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_hint', models.CharField(max_length=255)),
                ('ideas', models.TextField(blank=True, null=True)),
                ('picked', models.TextField(blank=True, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('research', models.TextField(blank=True, null=True)),
                ('draft', models.TextField(blank=True, null=True)),
                ('edited', models.TextField(blank=True, null=True)),
                ('seo', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('current_step', models.CharField(choices=[('ideas', 'Ideas'), ('pick', 'Pick'), ('brief', 'Brief'), ('research', 'Research'), ('draft', 'Draft'), ('edit', 'Edit'), ('seo', 'SEO'), ('html', 'HTML')], default='ideas', max_length=20)),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('completed', 'Completed'), ('failed', 'Failed')], default='drafting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
