# Generated by Django 5.2.6 on 2025-09-29 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_merge_20250929_1832"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("email_confirmed", "Email confirmed"),
                            ("checkout_started", "Checkout started"),
                            ("checkout_paid", "Checkout paid"),
                            ("scrape_queued", "Scrape queued"),
                            ("scrape_done", "Scrape done"),
                            ("reviews_queued", "Reviews queued"),
                            ("reviews_done", "Reviews done"),
                            ("web_analysis_done", "Web analysis done"),
                            ("review_analysis_done", "Review analysis done"),
                            ("personas_done", "Personas done"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "outscraper_search_job_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "outscraper_reviews_job_id",
                    models.CharField(blank=True, max_length=128),
                ),
                ("web_profile_json", models.JSONField(blank=True, null=True)),
                ("reviews_json", models.JSONField(blank=True, null=True)),
                ("review_analysis_json", models.JSONField(blank=True, null=True)),
                ("personas_json", models.JSONField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("accepted_terms", models.BooleanField(default=False)),
                ("accepted_privacy", models.BooleanField(default=False)),
                ("authorized_data_fetch", models.BooleanField(default=False)),
                (
                    "default_timezone",
                    models.CharField(default="America/Los_Angeles", max_length=64),
                ),
                ("default_currency", models.CharField(default="USD", max_length=8)),
                ("brand_color", models.CharField(default="#5C008B", max_length=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.restaurant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(max_length=50)),
                ("to_state", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.onboarding",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="onboarding",
            index=models.Index(
                fields=["state", "created_at"], name="app_onboard_state_03a105_idx"
            ),
        ),
    ]
