# Generated by Django 5.2.5 on 2025-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_onboarding_onboardingevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_view_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
