# Generated by Django 5.2.6 on 2025-09-30 12:03

from django.db import migrations, models


def set_default_view_mode(apps, schema_editor):
    UserProfile = apps.get_model("app", "UserProfile")
    UserProfile.objects.filter(preferred_view_mode__isnull=True).update(
        preferred_view_mode="list"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_userprofile_preferred_view_mode"),
    ]

    operations = [
        migrations.RunPython(set_default_view_mode, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_view_mode",
            field=models.CharField(blank=True, default="list", max_length=20),
        ),
    ]
