# Generated by Django 4.1.5 on 2025-09-04 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_subuserprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="plan",
        ),
        migrations.AddField(
            model_name="subscription",
            name="signup_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="trialing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
