# Generated by Django 5.2.6 on 2025-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userprofile_preferred_view_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
