# Generated by Django 4.1.5 on 2025-09-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_subscription_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                ("cta_clicks", models.IntegerField(default=0)),
                (
                    "special",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.special",
                    ),
                ),
            ],
        ),
    ]
