# Generated by Django 5.2.6 on 2025-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_activation_token_to_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
