# Generated by Django 4.1.5 on 2025-09-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_specialdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialdraft",
            name="concept",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="specialdraft",
            name="current_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="specialdraft",
            name="desc_status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("generating", "generating"),
                    ("ready", "ready"),
                    ("failed", "failed"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="specialdraft",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="specialdraft",
            name="image_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "uploaded"),
                    ("processing", "processing"),
                    ("ready", "ready"),
                    ("failed", "failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="specialdraft",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("once", "once"),
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                ],
                default="once",
                max_length=10,
            ),
        ),
    ]
