# Generated by ChatGPT

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_outscraperpayload_requested_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisioningJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_jobs",
                        to="app.onboarding",
                    ),
                ),
                ("stripe_session_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=50)),
                ("error", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_stripe_event_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["onboarding", "-created_at"]),
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [models.Index(fields=["-created_at"])],
            },
        ),
    ]
