# Generated by Django 5.2.5 on 2025-10-03 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_provisioningjob_stripewebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioningjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
