# Generated by Django 5.2.5 on 2025-10-03 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_provisioningjob_stripewebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provisioningjob',
            new_name='app_provisi_onboard_8e1ab0_idx',
            old_name='app_provisioningjob_onboarding_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='app_stripew_created_a077d9_idx',
            old_name='app_stripewebhookevent_created_idx',
        ),
        migrations.AlterField(
            model_name='provisioningjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
