# Generated by Django 5.2.5 on 2025-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_app_provisioningjob_onboarding_created_idx_app_provisi_onboard_8e1ab0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('email_confirmed', 'Email confirmed'), ('checkout_started', 'Checkout started'), ('checkout_paid', 'Checkout paid'), ('scrape_queued', 'Scrape queued'), ('scrape_done', 'Scrape done'), ('reviews_queued', 'Reviews queued'), ('reviews_done', 'Reviews done'), ('web_analysis_done', 'Web analysis done'), ('menu_done', 'Menu done'), ('review_analysis_done', 'Review analysis done'), ('personas_done', 'Personas done'), ('complete', 'Complete'), ('failed', 'Failed')], default='created', max_length=50),
        ),
    ]
