"""Mock LLM helper functions.

These stubs simulate calls to a large language model and return
static but structured data so the rest of the system can be
developed and tested without external dependencies.
"""

from typing import Dict, List


def generate_concepts() -> List[str]:
    """Return nine placeholder concept names."""
    return [f"Concept {i}" for i in range(1, 10)]


def generate_dishes(concept: str) -> List[Dict]:
    """Return nine placeholder dishes for a concept."""
    dishes: List[Dict] = []
    for i in range(1, 10):
        dishes.append(
            {
                "title": f"{concept} Dish {i}",
                "description": "Tasty dish generated by mock LLM.",
                "ingredient_overlap": [],
                "category_tags": ["tag"],
            }
        )
    return dishes


def enhance_dish(title: str) -> Dict:
    """Return placeholder enhancement data for a dish."""
    slug = title.lower().replace(" ", "-")
    return {"image_url": f"https://example.com/{slug}.jpg", "price": 12.0}
