"""Helpers for talking to LLM services.

The helpers in this module call out to third party APIs when keys are
configured and otherwise fall back to deterministic placeholder data so
tests can run without network access.
"""

from __future__ import annotations

import base64
import json
import logging
import os
import uuid
from typing import Dict, List, Optional
from google import genai
from google.genai import types
import requests
from openai import OpenAI

from dotenv import load_dotenv

from . import models

logger = logging.getLogger(__name__)

load_dotenv()

_openai_api_key = os.getenv("OPENAI_API_KEY")
_gemini_api_key = os.getenv("GEMINI_API_KEY")
logger.info(_gemini_api_key)
client = OpenAI(api_key=_openai_api_key) if _openai_api_key else None
gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
DEFAULT_IMAGE_URL = "https://placehold.co/800x600?text=Dish"
DEFAULT_PRICE_CENTS = 1500


def generate_dishes(concept: str) -> List[Dict]:
    """Return nine placeholder dishes for a concept."""
    dishes: List[Dict] = []
    for i in range(1, 10):
        dishes.append(
            {
                "title": f"{concept} Dish {i}",
                "description": "Tasty dish generated by mock LLM.",
                "ingredient_overlap": [],
                "category_tags": ["tag"],
            }
        )
    return dishes

def _gemini_image_prompt(title: str, description: str) -> str:
    return (
        "Create a realistic professional photograph of the following dish. "
        "Use a hero restaurant plating style, natural lighting, and a soft focus background.\n"
        f"Title: {title}\nDescription: {description}"
    )
    
def _call_gemini_for_image(title: str, description: str) -> str:
    """Return a data URL for the generated image using the Gemini SDK."""

    if not _gemini_api_key:
        return DEFAULT_IMAGE_URL

    try:
        # Build the prompt
        prompt = _gemini_image_prompt(title, description)

        # Call the image preview model
        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash-image-preview",
            contents=[prompt],
        )

        # Look for inline image data
        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data is not None:
                    image_bytes = part.inline_data.data
                    base64_data = base64.b64encode(image_bytes).decode("ascii")
                    return f"data:image/png;base64,{base64_data}"

        logger.warning("Gemini response did not include inline image data.")

    except Exception as exc:
        logger.warning("Gemini image generation failed: %s", exc, exc_info=True)

    return DEFAULT_IMAGE_URL


def _format_menu_snapshot(restaurant: models.Restaurant) -> Dict[str, Optional[str]]:
    menu_markdown = ""
    if restaurant.active_menu_version and restaurant.active_menu_version.raw_markdown:
        menu_markdown = restaurant.active_menu_version.raw_markdown
    return {
        "restaurant": restaurant.context_json or {},
        "menu_markdown": menu_markdown,
    }


def _call_openai_for_price(
    dish: models.DishIdea, menu_snapshot: Dict[str, Optional[str]]
) -> Dict[str, Optional[str]]:
    """Return pricing info using OpenAI or deterministic fallback."""

    fallback = {
        "price_cents": DEFAULT_PRICE_CENTS,
        "currency": "USD",
        "rationale": "LLM unavailable, using baseline price.",
    }

    if not client:
        return fallback

    schema = {
        "name": "enhanced_price",
        "type": "json_schema",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "price_cents": {"type": "integer"},
                "currency": {"type": "string"},
                "rationale": {"type": "string"},
            },
            "required": ["price_cents", "currency", "rationale"],
            "additionalProperties": False,
        },
    }

    payload = {
        "dish": {
            "title": dish.title,
            "description": dish.description,
            "ingredients": list(dish.ingredient_names or []),
            "categories": list(dish.category_tags or []),
        },
        "restaurant": menu_snapshot.get("restaurant", {}),
        "menu_markdown": menu_snapshot.get("menu_markdown", ""),
    }

    try:
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=[
                {
                    "role": "system",
                    "content": (
                        "You are a pricing analyst for a restaurant. "
                        "Suggest a menu price in cents considering the context, menu, and ingredients."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(payload, indent=2),
                },
            ],
            text={"format": schema},
        )
        raw_text = response.output[0].content[0].text
        data = json.loads(raw_text)
        price_cents = int(data.get("price_cents", fallback["price_cents"]))
        currency = data.get("currency") or fallback["currency"]
        rationale = data.get("rationale") or fallback["rationale"]
        return {
            "price_cents": price_cents,
            "currency": currency,
            "rationale": rationale,
        }
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning("OpenAI pricing request failed: %s", exc, exc_info=True)
        return fallback


def enhance_dish(dish: models.DishIdea, restaurant: models.Restaurant) -> Dict[str, Optional[str]]:
    """Generate enhanced mode assets for a dish."""

    image_url = _call_gemini_for_image(dish.title, dish.description)
    snapshot = _format_menu_snapshot(restaurant)
    price_info = _call_openai_for_price(dish, snapshot)

    return {
        "image_url": image_url,
        "price_cents": price_info.get("price_cents"),
        "currency": price_info.get("currency"),
        "pricing_notes": price_info.get("rationale"),
        "style_preset": "enhanced-mode-v1",
        "model_name": "gemini+openai-enhanced",
        "snapshot": snapshot,
        "reference": str(uuid.uuid4()),
    }
