# Generated by Django 5.2.7 on 2025-11-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
