# Generated by Django 5.2.7 on 2025-11-09 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0002_restaurant_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('scope', models.CharField(blank=True, max_length=200, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('est_cost_usd', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('review_id', models.CharField(db_index=True, max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='avg_review_gap_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='next_fetch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(db_index=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'active'], name='gastronet_r_city_8e1d35_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['next_fetch_at'], name='gastronet_r_next_fe_eb2f1f_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gastronet.restaurant'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant', 'created_at'], name='gastronet_r_restaur_d01639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant', 'source', 'review_id')},
        ),
    ]
