# Generated by Django 5.2.7 on 2025-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0003_crawllog_review_restaurant_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
