# Generated by Django 5.2.7 on 2025-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0004_restaurant_menu_url_restaurant_url_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('result_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=1)),
            ],
        ),
    ]
