# Generated by Django 5.2.7 on 2025-11-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0005_urldiscovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('found', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_attempts', to='gastronet.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='gastronet.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'category'], name='gastronet_m_restaur_5b3e7b_idx')],
            },
        ),
    ]
