# Generated by Django 5.2.7 on 2025-11-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0006_menuattempt_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField()),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=64)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastronet.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
