# Generated by Django 5.2.7 on 2025-11-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0007_menusnapshot_delete_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusnapshot',
            name='render_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menusnapshot',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusnapshot',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_snapshots', to='gastronet.restaurant'),
        ),
    ]
