# Generated by Django 5.2.7 on 2025-11-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0008_menusnapshot_render_method_menusnapshot_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
