# Generated by Django 5.2.7 on 2025-11-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0009_restaurant_about_restaurant_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
