# Generated by Django 5.2.7 on 2025-11-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0010_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(db_index=True, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
