# Generated by Django 5.2.7 on 2025-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0011_alter_restaurant_category_alter_restaurant_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='booking_appointment_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_view',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reviews_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
