# Generated by Django 5.2.7 on 2025-11-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0012_restaurant_booking_appointment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='gastronet.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'source_url', 'name')},
            },
        ),
    ]
