# Generated by Django 5.2.7 on 2025-10-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank_order', models.SmallIntegerField()),
                ('enhanced', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rank_order'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('fetching', 'Fetching leads'), ('preparing', 'Preparing demos'), ('ready', 'Ready for review'), ('completed', 'Completed')], default='created', max_length=20)),
                ('outscraper_job_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('expected_leads', models.PositiveIntegerField(default=10)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('processed_leads', models.PositiveIntegerField(default=0)),
                ('selected_leads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('landing_url', models.URLField(blank=True, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('price_level', models.CharField(blank=True, max_length=20, null=True)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('menu_links', models.JSONField(blank=True, default=list)),
                ('order_links', models.JSONField(blank=True, default=list)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('json_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('email_bounced', models.BooleanField(default=False)),
                ('followed_up', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app.restaurant')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leadrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('favorited', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='leads.concept')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='leads.lead')),
            ],
            options={
                'ordering': ['-favorited', 'id'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='leads.lead'),
        ),
    ]
