# Generated by Django 5.2.6 on 2025-09-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("fetching", "Fetching leads"),
                            ("preparing", "Preparing demos"),
                            ("ready", "Ready for review"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("expected_leads", models.PositiveIntegerField(default=10)),
                ("total_leads", models.PositiveIntegerField(default=0)),
                ("processed_leads", models.PositiveIntegerField(default=0)),
                ("selected_leads", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="shortlisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="leads.leadrun",
            ),
        ),
    ]
