# Generated by Django 5.2.6 on 2025-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_leadrun_outscraper_job_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("subject", models.CharField(max_length=200)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="email_bounced",
            field=models.BooleanField(default=False),
        ),
    ]
