# Generated by Django 5.2.7 on 2025-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_emailtemplate_lead_email_bounced"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="emails",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lead",
            name="full_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="menu_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lead",
            name="order_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lead",
            name="phones",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lead",
            name="price_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="review_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
